{% set name = "eosets" %}
{% set version = "0.3.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/eosets-{{ version }}.tar.gz
  sha256: 7fbc8203b5477496b6319e63b41f9537f74eb3db0ec6d95ac59b2db91a3c68c1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - geopandas >=0.14.4
    - lxml
    - h5netcdf
    - rasterio >=1.3.10
    - xarray >=2024.06.0
    - rioxarray >=0.10.0
    - rtree
    - cloudpathlib >=0.12.1
    - sertit >=1.44.6
    - eoreader >=0.21.9
    - validators
    - matplotlib-base
    - methodtools
    - pystac
    - spyndex >=0.3.0
    - pyresample
    - zarr
    - dicttoxml


test:
  imports:
    - eosets
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: http://github.com/sertit/eosets/
  summary: This library aims to simplify any process working with sets of EO data handled by EOReader.
  license: Apache-2.0
  license_file: LICENSE
  description: This library aims to simplify any process working with sets of EO data handled by EOReader.
  doc_url: https://eosets.readthedocs.io/en/latest/
  dev_url: http://github.com/sertit/eosets

extra:
  recipe-maintainers:
    - bastiencyr
    - qpoterek
    - remi-braun
