{% set name = "eosets" %}
{% set version = "0.2.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/eosets-{{ version }}.tar.gz
  sha256: c52f7c7640832f1b6e7f32670b68e61db8a8eeecbb9053d0fd3f01ecda7b0296

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools
    - python >=3.9
  run:
    - geopandas >=0.14.4
    - lxml
    - h5netcdf
    - python >=3.9
    - rasterio >=1.3.10
    - xarray >=2024.06.0
    - rioxarray >=0.10.0
    - rtree
    - cloudpathlib >=0.12.1
    - sertit >=1.42.2
    - eoreader >=0.21.3
    - validators
    - matplotlib-base
    - methodtools
    - pystac
    - spyndex >=0.3.0
    - pyresample
    - zarr
    - dicttoxml


test:
  imports:
    - eosets
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/sertit/eosets/
  summary: This library aims to simplify any process working with sets of EO data handled by EOReader.
  license: Apache-2.0
  license_file: LICENSE
  description: This library aims to simplify any process working with sets of EO data handled by EOReader.
  doc_url: https://eosets.readthedocs.io/en/latest/
  dev_url: http://github.com/sertit/eosets

extra:
  recipe-maintainers:
    - remi-braun
