{% set name = "eosets" %}
{% set version = "0.5.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/eosets-{{ version }}.tar.gz
  sha256: 2815b65c5c53d405d46faabcd1fb85ce14d3f25fcc754bc2a3841dba602b0846

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - geopandas >=0.14.4
    - rasterio >=1.3.10
    - xarray >=2024.06.0
    - rioxarray >=0.15.0
    - cloudpathlib-s3 >=0.15.0
    - sertit >=1.50.2
    - eoreader >=0.23.0
    - matplotlib-base
    - pystac

test:
  imports:
    - eosets
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: http://github.com/sertit/eosets/
  summary: This library aims to simplify any process working with sets of EO data handled by EOReader.
  license: Apache-2.0
  license_file: LICENSE
  description: This library aims to simplify any process working with sets of EO data handled by EOReader.
  doc_url: https://eosets.readthedocs.io/en/latest/
  dev_url: http://github.com/sertit/eosets

extra:
  recipe-maintainers:
    - Alt-o
    - qpoterek
    - remi-braun
