{% set name = "eosets" %}
{% set version = "0.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/eosets-{{ version }}.tar.gz
  sha256: 9df62f4b3145a493f5f72245c720b218189e238638dbfc4c39f8ef5ab8f083fc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - geopandas >=0.11.0
    - lxml
    - h5netcdf
    - python >=3.9
    - rasterio >=1.3.0
    - xarray >=0.18.0
    - rioxarray >=0.10.0
    - rtree
    - cloudpathlib >=0.10.0
    - sertit >=1.27.3
    - eoreader >=0.20.3
    - validators
    - matplotlib-base
    - methodtools
    - pystac
    - spyndex >=0.3.0
    - pyresample
    - zarr
    - dicttoxml


test:
  imports:
    - eosets
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/sertit/eosets/
  summary: This library aims to simplify any process working with sets of EO data handled by EOReader.
  license: Apache-2.0
  license_file: LICENSE
  description: This library aims to simplify any process working with sets of EO data handled by EOReader.
  doc_url: https://eosets.readthedocs.io/en/latest/
  dev_url: http://github.com/sertit/eosets

extra:
  recipe-maintainers:
    - remi-braun
